package tw.com.imsoft.dao.mapper;

import tw.com.imsoft.dao.model.Member;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    int deleteByPrimaryKey(String memId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    Member selectByPrimaryKey(String memId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    int updateByPrimaryKey(Member record);
}