spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  datasource:
    url: jdbc:oracle:thin:@//61.216.84.217:1534/ORCL
    username: line
    password: 123456
    daiver-class-name: oracle.jdbc.OracleDriver
      
      
server:
  servlet:
    context-path: /onlineOrder
  port: 8081