package tw.com.imsoft.dao.model;

import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Member implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEM_ID
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    private String memId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.LINE_ID
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    private String lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEM_NAME
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    private String memName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEN_PWD
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    private String menPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER
     *
     * @mbg.generated Thu Apr 27 17:22:44 CST 2023
     */
    private static final long serialVersionUID = 1L;
}